use super::cmn::OpCodeInfo;

/*
To regenerate this run
gc -Raw "D:\src\u\s\emu\src\cpu\opcodes.json" | ConvertFrom-Json | sort -Property opc | % { '    /* 0x{0:x2} */ OpCodeInfo {{ addressing: "{1}", assembler: "{2}", bytes: {3}, cycles: "{4}" }},' -f ($_.opc, $_.addressing, $_.assembler, $_.bytes, $_.cycles) }
*/
/// NOTE: See opcodes.json
#[rustfmt::skip]
pub const ALL: &[OpCodeInfo; 0x1_00] = &[
    /* 0x00 */ OpCodeInfo { addressing: "impl", assembler: "BRK", bytes: 1, cycles: "7" },
    /* 0x01 */ OpCodeInfo { addressing: "X,ind", assembler: "ORA ($LL,X)", bytes: 2, cycles: "6" },
    /* 0x02 */ OpCodeInfo { addressing: "impl", assembler: "JAM", bytes: 1, cycles: "X" },
    /* 0x03 */ OpCodeInfo { addressing: "X,ind", assembler: "SLO ($LL,X)", bytes: 2, cycles: "8" },
    /* 0x04 */ OpCodeInfo { addressing: "zpg", assembler: "NOP $LL", bytes: 2, cycles: "3" },
    /* 0x05 */ OpCodeInfo { addressing: "zpg", assembler: "ORA $LL", bytes: 2, cycles: "3" },
    /* 0x06 */ OpCodeInfo { addressing: "zpg", assembler: "ASL $LL", bytes: 2, cycles: "5" },
    /* 0x07 */ OpCodeInfo { addressing: "zpg", assembler: "SLO $LL", bytes: 2, cycles: "5" },
    /* 0x08 */ OpCodeInfo { addressing: "impl", assembler: "PHP", bytes: 1, cycles: "3" },
    /* 0x09 */ OpCodeInfo { addressing: "#", assembler: "ORA #$LL", bytes: 2, cycles: "2" },
    /* 0x0A */ OpCodeInfo { addressing: "acc", assembler: "ASL A", bytes: 1, cycles: "2" },
    /* 0x0B */ OpCodeInfo { addressing: "#", assembler: "ANC #$LL", bytes: 2, cycles: "2" },
    /* 0x0C */ OpCodeInfo { addressing: "abs", assembler: "NOP $LLHH", bytes: 3, cycles: "4" },
    /* 0x0D */ OpCodeInfo { addressing: "abs", assembler: "ORA $LLHH", bytes: 3, cycles: "4" },
    /* 0x0E */ OpCodeInfo { addressing: "abs", assembler: "ASL $LLHH", bytes: 3, cycles: "6" },
    /* 0x0F */ OpCodeInfo { addressing: "abs", assembler: "SLO $LLHH", bytes: 3, cycles: "6" },
    /* 0x10 */ OpCodeInfo { addressing: "rel", assembler: "BPL $LLHH", bytes: 2, cycles: "2+t+p" },
    /* 0x11 */ OpCodeInfo { addressing: "ind,Y", assembler: "ORA ($LL),Y", bytes: 2, cycles: "5+p" },
    /* 0x12 */ OpCodeInfo { addressing: "impl", assembler: "JAM", bytes: 1, cycles: "X" },
    /* 0x13 */ OpCodeInfo { addressing: "ind,Y", assembler: "SLO ($LL),Y", bytes: 2, cycles: "8" },
    /* 0x14 */ OpCodeInfo { addressing: "zpg,X", assembler: "NOP $LL,X", bytes: 2, cycles: "4" },
    /* 0x15 */ OpCodeInfo { addressing: "zpg,X", assembler: "ORA $LL,X", bytes: 2, cycles: "4" },
    /* 0x16 */ OpCodeInfo { addressing: "zpg,X", assembler: "ASL $LL,X", bytes: 2, cycles: "6" },
    /* 0x17 */ OpCodeInfo { addressing: "zpg,X", assembler: "SLO $LL,X", bytes: 2, cycles: "6" },
    /* 0x18 */ OpCodeInfo { addressing: "impl", assembler: "CLC", bytes: 1, cycles: "2" },
    /* 0x19 */ OpCodeInfo { addressing: "abs,Y", assembler: "ORA $LLHH,Y", bytes: 3, cycles: "4+p" },
    /* 0x1A */ OpCodeInfo { addressing: "impl", assembler: "NOP", bytes: 1, cycles: "2" },
    /* 0x1B */ OpCodeInfo { addressing: "abs,Y", assembler: "SLO $LLHH,Y", bytes: 3, cycles: "7" },
    /* 0x1C */ OpCodeInfo { addressing: "abs,X", assembler: "NOP $LLHH,X", bytes: 3, cycles: "4+p" },
    /* 0x1D */ OpCodeInfo { addressing: "abs,X", assembler: "ORA $LLHH,X", bytes: 3, cycles: "4+p" },
    /* 0x1E */ OpCodeInfo { addressing: "abs,X", assembler: "ASL $LLHH,X", bytes: 3, cycles: "7" },
    /* 0x1F */ OpCodeInfo { addressing: "abs,X", assembler: "SLO $LLHH,X", bytes: 3, cycles: "7" },
    /* 0x20 */ OpCodeInfo { addressing: "abs", assembler: "JSR $LLHH", bytes: 3, cycles: "6" },
    /* 0x21 */ OpCodeInfo { addressing: "X,ind", assembler: "AND ($LL,X)", bytes: 2, cycles: "6" },
    /* 0x22 */ OpCodeInfo { addressing: "impl", assembler: "JAM", bytes: 1, cycles: "X" },
    /* 0x23 */ OpCodeInfo { addressing: "X,ind", assembler: "RLA ($LL,X)", bytes: 2, cycles: "8" },
    /* 0x24 */ OpCodeInfo { addressing: "zpg", assembler: "BIT $LL", bytes: 2, cycles: "3" },
    /* 0x25 */ OpCodeInfo { addressing: "zpg", assembler: "AND $LL", bytes: 2, cycles: "3" },
    /* 0x26 */ OpCodeInfo { addressing: "zpg", assembler: "ROL $LL", bytes: 2, cycles: "5" },
    /* 0x27 */ OpCodeInfo { addressing: "zpg", assembler: "RLA $LL", bytes: 2, cycles: "5" },
    /* 0x28 */ OpCodeInfo { addressing: "impl", assembler: "PLP", bytes: 1, cycles: "4" },
    /* 0x29 */ OpCodeInfo { addressing: "#", assembler: "AND #$LL", bytes: 2, cycles: "2" },
    /* 0x2A */ OpCodeInfo { addressing: "acc", assembler: "ROL A", bytes: 1, cycles: "2" },
    /* 0x2B */ OpCodeInfo { addressing: "#", assembler: "ANC #$LL", bytes: 2, cycles: "2" },
    /* 0x2C */ OpCodeInfo { addressing: "abs", assembler: "BIT $LLHH", bytes: 3, cycles: "4" },
    /* 0x2D */ OpCodeInfo { addressing: "abs", assembler: "AND $LLHH", bytes: 3, cycles: "4" },
    /* 0x2E */ OpCodeInfo { addressing: "abs", assembler: "ROL $LLHH", bytes: 3, cycles: "6" },
    /* 0x2F */ OpCodeInfo { addressing: "abs", assembler: "RLA $LLHH", bytes: 3, cycles: "6" },
    /* 0x30 */ OpCodeInfo { addressing: "rel", assembler: "BMI $LLHH", bytes: 2, cycles: "2+t+p" },
    /* 0x31 */ OpCodeInfo { addressing: "ind,Y", assembler: "AND ($LL),Y", bytes: 2, cycles: "5+p" },
    /* 0x32 */ OpCodeInfo { addressing: "impl", assembler: "JAM", bytes: 1, cycles: "X" },
    /* 0x33 */ OpCodeInfo { addressing: "ind,Y", assembler: "RLA ($LL),Y", bytes: 2, cycles: "8" },
    /* 0x34 */ OpCodeInfo { addressing: "zpg,X", assembler: "NOP $LL,X", bytes: 2, cycles: "4" },
    /* 0x35 */ OpCodeInfo { addressing: "zpg,X", assembler: "AND $LL,X", bytes: 2, cycles: "4" },
    /* 0x36 */ OpCodeInfo { addressing: "zpg,X", assembler: "ROL $LL,X", bytes: 2, cycles: "6" },
    /* 0x37 */ OpCodeInfo { addressing: "zpg,X", assembler: "RLA $LL,X", bytes: 2, cycles: "6" },
    /* 0x38 */ OpCodeInfo { addressing: "impl", assembler: "SEC", bytes: 1, cycles: "2" },
    /* 0x39 */ OpCodeInfo { addressing: "abs,Y", assembler: "AND $LLHH,Y", bytes: 3, cycles: "4+p" },
    /* 0x3A */ OpCodeInfo { addressing: "impl", assembler: "NOP", bytes: 1, cycles: "2" },
    /* 0x3B */ OpCodeInfo { addressing: "abs,Y", assembler: "RLA $LLHH,Y", bytes: 3, cycles: "7" },
    /* 0x3C */ OpCodeInfo { addressing: "abs,X", assembler: "NOP $LLHH,X", bytes: 3, cycles: "4+p" },
    /* 0x3D */ OpCodeInfo { addressing: "abs,X", assembler: "AND $LLHH,X", bytes: 3, cycles: "4+p" },
    /* 0x3E */ OpCodeInfo { addressing: "abs,X", assembler: "ROL $LLHH,X", bytes: 3, cycles: "7" },
    /* 0x3F */ OpCodeInfo { addressing: "abs,X", assembler: "RLA $LLHH,X", bytes: 3, cycles: "7" },
    /* 0x40 */ OpCodeInfo { addressing: "impl", assembler: "RTI", bytes: 1, cycles: "6" },
    /* 0x41 */ OpCodeInfo { addressing: "X,ind", assembler: "EOR ($LL,X)", bytes: 2, cycles: "6" },
    /* 0x42 */ OpCodeInfo { addressing: "impl", assembler: "JAM", bytes: 1, cycles: "X" },
    /* 0x43 */ OpCodeInfo { addressing: "X,ind", assembler: "SRE ($LL,X)", bytes: 2, cycles: "8" },
    /* 0x44 */ OpCodeInfo { addressing: "zpg", assembler: "NOP $LL", bytes: 2, cycles: "3" },
    /* 0x45 */ OpCodeInfo { addressing: "zpg", assembler: "EOR $LL", bytes: 2, cycles: "3" },
    /* 0x46 */ OpCodeInfo { addressing: "zpg", assembler: "LSR $LL", bytes: 2, cycles: "5" },
    /* 0x47 */ OpCodeInfo { addressing: "zpg", assembler: "SRE $LL", bytes: 2, cycles: "5" },
    /* 0x48 */ OpCodeInfo { addressing: "impl", assembler: "PHA", bytes: 1, cycles: "3" },
    /* 0x49 */ OpCodeInfo { addressing: "#", assembler: "EOR #$LL", bytes: 2, cycles: "2" },
    /* 0x4A */ OpCodeInfo { addressing: "acc", assembler: "LSR A", bytes: 1, cycles: "2" },
    /* 0x4B */ OpCodeInfo { addressing: "#", assembler: "ASR #$LL", bytes: 2, cycles: "2" },
    /* 0x4C */ OpCodeInfo { addressing: "abs", assembler: "JMP $LLHH", bytes: 3, cycles: "3" },
    /* 0x4D */ OpCodeInfo { addressing: "abs", assembler: "EOR $LLHH", bytes: 3, cycles: "4" },
    /* 0x4E */ OpCodeInfo { addressing: "abs", assembler: "LSR $LLHH", bytes: 3, cycles: "6" },
    /* 0x4F */ OpCodeInfo { addressing: "abs", assembler: "SRE $LLHH", bytes: 3, cycles: "6" },
    /* 0x50 */ OpCodeInfo { addressing: "rel", assembler: "BVC $LLHH", bytes: 2, cycles: "2+t+p" },
    /* 0x51 */ OpCodeInfo { addressing: "ind,Y", assembler: "EOR ($LL),Y", bytes: 2, cycles: "5+p" },
    /* 0x52 */ OpCodeInfo { addressing: "impl", assembler: "JAM", bytes: 1, cycles: "X" },
    /* 0x53 */ OpCodeInfo { addressing: "ind,Y", assembler: "SRE ($LL),Y", bytes: 2, cycles: "8" },
    /* 0x54 */ OpCodeInfo { addressing: "zpg,X", assembler: "NOP $LL,X", bytes: 2, cycles: "4" },
    /* 0x55 */ OpCodeInfo { addressing: "zpg,X", assembler: "EOR $LL,X", bytes: 2, cycles: "4" },
    /* 0x56 */ OpCodeInfo { addressing: "zpg,X", assembler: "LSR $LL,X", bytes: 2, cycles: "6" },
    /* 0x57 */ OpCodeInfo { addressing: "zpg,X", assembler: "SRE $LL,X", bytes: 2, cycles: "6" },
    /* 0x58 */ OpCodeInfo { addressing: "impl", assembler: "CLI", bytes: 1, cycles: "2" },
    /* 0x59 */ OpCodeInfo { addressing: "abs,Y", assembler: "EOR $LLHH,Y", bytes: 3, cycles: "4+p" },
    /* 0x5A */ OpCodeInfo { addressing: "impl", assembler: "NOP", bytes: 1, cycles: "2" },
    /* 0x5B */ OpCodeInfo { addressing: "abs,Y", assembler: "SRE $LLHH,Y", bytes: 3, cycles: "7" },
    /* 0x5C */ OpCodeInfo { addressing: "abs,X", assembler: "NOP $LLHH,X", bytes: 3, cycles: "4+p" },
    /* 0x5D */ OpCodeInfo { addressing: "abs,X", assembler: "EOR $LLHH,X", bytes: 3, cycles: "4+p" },
    /* 0x5E */ OpCodeInfo { addressing: "abs,X", assembler: "LSR $LLHH,X", bytes: 3, cycles: "7" },
    /* 0x5F */ OpCodeInfo { addressing: "abs,X", assembler: "SRE $LLHH,X", bytes: 3, cycles: "7" },
    /* 0x60 */ OpCodeInfo { addressing: "impl", assembler: "RTS", bytes: 1, cycles: "6" },
    /* 0x61 */ OpCodeInfo { addressing: "X,ind", assembler: "ADC ($LL,X)", bytes: 2, cycles: "6" },
    /* 0x62 */ OpCodeInfo { addressing: "impl", assembler: "JAM", bytes: 1, cycles: "X" },
    /* 0x63 */ OpCodeInfo { addressing: "X,ind", assembler: "RRA ($LL,X)", bytes: 2, cycles: "8" },
    /* 0x64 */ OpCodeInfo { addressing: "zpg", assembler: "NOP $LL", bytes: 2, cycles: "3" },
    /* 0x65 */ OpCodeInfo { addressing: "zpg", assembler: "ADC $LL", bytes: 2, cycles: "3" },
    /* 0x66 */ OpCodeInfo { addressing: "zpg", assembler: "ROR $LL", bytes: 2, cycles: "5" },
    /* 0x67 */ OpCodeInfo { addressing: "zpg", assembler: "RRA $LL", bytes: 2, cycles: "5" },
    /* 0x68 */ OpCodeInfo { addressing: "impl", assembler: "PLA", bytes: 1, cycles: "4" },
    /* 0x69 */ OpCodeInfo { addressing: "#", assembler: "ADC #$LL", bytes: 2, cycles: "2" },
    /* 0x6A */ OpCodeInfo { addressing: "acc", assembler: "ROR A", bytes: 1, cycles: "2" },
    /* 0x6B */ OpCodeInfo { addressing: "#", assembler: "ARR #$LL", bytes: 2, cycles: "2" },
    /* 0x6C */ OpCodeInfo { addressing: "abs ind", assembler: "JMP ($LLHH)", bytes: 3, cycles: "5" },
    /* 0x6D */ OpCodeInfo { addressing: "abs", assembler: "ADC $LLHH", bytes: 3, cycles: "4" },
    /* 0x6E */ OpCodeInfo { addressing: "abs", assembler: "ROR $LLHH", bytes: 3, cycles: "6" },
    /* 0x6F */ OpCodeInfo { addressing: "abs", assembler: "RRA $LLHH", bytes: 3, cycles: "6" },
    /* 0x70 */ OpCodeInfo { addressing: "rel", assembler: "BVS $LLHH", bytes: 2, cycles: "2+t+p" },
    /* 0x71 */ OpCodeInfo { addressing: "ind,Y", assembler: "ADC ($LL),Y", bytes: 2, cycles: "5+p" },
    /* 0x72 */ OpCodeInfo { addressing: "impl", assembler: "JAM", bytes: 1, cycles: "X" },
    /* 0x73 */ OpCodeInfo { addressing: "ind,Y", assembler: "RRA ($LL),Y", bytes: 2, cycles: "8" },
    /* 0x74 */ OpCodeInfo { addressing: "zpg,X", assembler: "NOP $LL,X", bytes: 2, cycles: "4" },
    /* 0x75 */ OpCodeInfo { addressing: "zpg,X", assembler: "ADC $LL,X", bytes: 2, cycles: "4" },
    /* 0x76 */ OpCodeInfo { addressing: "zpg,X", assembler: "ROR $LL,X", bytes: 2, cycles: "6" },
    /* 0x77 */ OpCodeInfo { addressing: "zpg,X", assembler: "RRA $LL,X", bytes: 2, cycles: "6" },
    /* 0x78 */ OpCodeInfo { addressing: "impl", assembler: "SEI", bytes: 1, cycles: "2" },
    /* 0x79 */ OpCodeInfo { addressing: "abs,Y", assembler: "ADC $LLHH,Y", bytes: 3, cycles: "4+p" },
    /* 0x7A */ OpCodeInfo { addressing: "impl", assembler: "NOP", bytes: 1, cycles: "2" },
    /* 0x7B */ OpCodeInfo { addressing: "abs,Y", assembler: "RRA $LLHH,Y", bytes: 3, cycles: "7" },
    /* 0x7C */ OpCodeInfo { addressing: "abs,X", assembler: "NOP $LLHH,X", bytes: 3, cycles: "4+p" },
    /* 0x7D */ OpCodeInfo { addressing: "abs,X", assembler: "ADC $LLHH,X", bytes: 3, cycles: "4+p" },
    /* 0x7E */ OpCodeInfo { addressing: "abs,X", assembler: "ROR $LLHH,X", bytes: 3, cycles: "7" },
    /* 0x7F */ OpCodeInfo { addressing: "abs,X", assembler: "RRA $LLHH,X", bytes: 3, cycles: "7" },
    /* 0x80 */ OpCodeInfo { addressing: "#", assembler: "NOP #$LL", bytes: 2, cycles: "2" },
    /* 0x81 */ OpCodeInfo { addressing: "X,ind", assembler: "STA ($LL,X)", bytes: 2, cycles: "6" },
    /* 0x82 */ OpCodeInfo { addressing: "#", assembler: "NOP #$LL", bytes: 2, cycles: "2" },
    /* 0x83 */ OpCodeInfo { addressing: "X,ind", assembler: "SAX ($LL,X)", bytes: 2, cycles: "6" },
    /* 0x84 */ OpCodeInfo { addressing: "zpg", assembler: "STY $LL", bytes: 2, cycles: "3" },
    /* 0x85 */ OpCodeInfo { addressing: "zpg", assembler: "STA $LL", bytes: 2, cycles: "3" },
    /* 0x86 */ OpCodeInfo { addressing: "zpg", assembler: "STX $LL", bytes: 2, cycles: "3" },
    /* 0x87 */ OpCodeInfo { addressing: "zpg", assembler: "SAX $LL", bytes: 2, cycles: "3" },
    /* 0x88 */ OpCodeInfo { addressing: "impl", assembler: "DEY", bytes: 1, cycles: "2" },
    /* 0x89 */ OpCodeInfo { addressing: "#", assembler: "NOP #$LL", bytes: 2, cycles: "2" },
    /* 0x8A */ OpCodeInfo { addressing: "impl", assembler: "TXA", bytes: 1, cycles: "2" },
    /* 0x8B */ OpCodeInfo { addressing: "#", assembler: "XAA #$LL", bytes: 2, cycles: "2" },
    /* 0x8C */ OpCodeInfo { addressing: "abs", assembler: "STY $LLHH", bytes: 3, cycles: "4" },
    /* 0x8D */ OpCodeInfo { addressing: "abs", assembler: "STA $LLHH", bytes: 3, cycles: "4" },
    /* 0x8E */ OpCodeInfo { addressing: "abs", assembler: "STX $LLHH", bytes: 3, cycles: "4" },
    /* 0x8F */ OpCodeInfo { addressing: "abs", assembler: "SAX $LLHH", bytes: 3, cycles: "4" },
    /* 0x90 */ OpCodeInfo { addressing: "rel", assembler: "BCC $LLHH", bytes: 2, cycles: "2+t+p" },
    /* 0x91 */ OpCodeInfo { addressing: "ind,Y", assembler: "STA ($LL),Y", bytes: 2, cycles: "6" },
    /* 0x92 */ OpCodeInfo { addressing: "impl", assembler: "JAM", bytes: 1, cycles: "X" },
    /* 0x93 */ OpCodeInfo { addressing: "ind,Y", assembler: "SHA ($LL),Y", bytes: 2, cycles: "6" },
    /* 0x94 */ OpCodeInfo { addressing: "zpg,X", assembler: "STY $LL,X", bytes: 2, cycles: "4" },
    /* 0x95 */ OpCodeInfo { addressing: "zpg,X", assembler: "STA $LL,X", bytes: 2, cycles: "4" },
    /* 0x96 */ OpCodeInfo { addressing: "zpg,Y", assembler: "STX $LL,Y", bytes: 2, cycles: "4" },
    /* 0x97 */ OpCodeInfo { addressing: "zpg,Y", assembler: "SAX $LL,Y", bytes: 2, cycles: "4" },
    /* 0x98 */ OpCodeInfo { addressing: "impl", assembler: "TYA", bytes: 1, cycles: "2" },
    /* 0x99 */ OpCodeInfo { addressing: "abs,Y", assembler: "STA $LLHH,Y", bytes: 3, cycles: "5" },
    /* 0x9A */ OpCodeInfo { addressing: "impl", assembler: "TXS", bytes: 1, cycles: "2" },
    /* 0x9B */ OpCodeInfo { addressing: "abs,Y", assembler: "SHS $LLHH,Y", bytes: 3, cycles: "5" },
    /* 0x9C */ OpCodeInfo { addressing: "abs,X", assembler: "SHY $LLHH,X", bytes: 3, cycles: "5" },
    /* 0x9D */ OpCodeInfo { addressing: "abs,X", assembler: "STA $LLHH,X", bytes: 3, cycles: "5" },
    /* 0x9E */ OpCodeInfo { addressing: "abs,Y", assembler: "SHX $LLHH,Y", bytes: 3, cycles: "5" },
    /* 0x9F */ OpCodeInfo { addressing: "abs,Y", assembler: "SHA $LLHH,Y", bytes: 3, cycles: "5" },
    /* 0xA0 */ OpCodeInfo { addressing: "#", assembler: "LDY #$LL", bytes: 2, cycles: "2" },
    /* 0xA1 */ OpCodeInfo { addressing: "X,ind", assembler: "LDA ($LL,X)", bytes: 2, cycles: "6" },
    /* 0xA2 */ OpCodeInfo { addressing: "#", assembler: "LDX #$LL", bytes: 2, cycles: "2" },
    /* 0xA3 */ OpCodeInfo { addressing: "X,ind", assembler: "LAX ($LL,X)", bytes: 2, cycles: "6" },
    /* 0xA4 */ OpCodeInfo { addressing: "zpg", assembler: "LDY $LL", bytes: 2, cycles: "3" },
    /* 0xA5 */ OpCodeInfo { addressing: "zpg", assembler: "LDA $LL", bytes: 2, cycles: "3" },
    /* 0xA6 */ OpCodeInfo { addressing: "zpg", assembler: "LDX $LL", bytes: 2, cycles: "3" },
    /* 0xA7 */ OpCodeInfo { addressing: "zpg", assembler: "LAX $LL", bytes: 2, cycles: "3" },
    /* 0xA8 */ OpCodeInfo { addressing: "impl", assembler: "TAY", bytes: 1, cycles: "2" },
    /* 0xA9 */ OpCodeInfo { addressing: "#", assembler: "LDA #$LL", bytes: 2, cycles: "2" },
    /* 0xAA */ OpCodeInfo { addressing: "impl", assembler: "TAX", bytes: 1, cycles: "2" },
    /* 0xAB */ OpCodeInfo { addressing: "#", assembler: "LAX #$LL", bytes: 2, cycles: "2" },
    /* 0xAC */ OpCodeInfo { addressing: "abs", assembler: "LDY $LLHH", bytes: 3, cycles: "4" },
    /* 0xAD */ OpCodeInfo { addressing: "abs", assembler: "LDA $LLHH", bytes: 3, cycles: "4" },
    /* 0xAE */ OpCodeInfo { addressing: "abs", assembler: "LDX $LLHH", bytes: 3, cycles: "4" },
    /* 0xAF */ OpCodeInfo { addressing: "abs", assembler: "LAX $LLHH", bytes: 3, cycles: "4" },
    /* 0xB0 */ OpCodeInfo { addressing: "rel", assembler: "BCS $LLHH", bytes: 2, cycles: "2+t+p" },
    /* 0xB1 */ OpCodeInfo { addressing: "ind,Y", assembler: "LDA ($LL),Y", bytes: 2, cycles: "5+p" },
    /* 0xB2 */ OpCodeInfo { addressing: "impl", assembler: "JAM", bytes: 1, cycles: "X" },
    /* 0xB3 */ OpCodeInfo { addressing: "ind,Y", assembler: "LAX ($LL),Y", bytes: 2, cycles: "5+p" },
    /* 0xB4 */ OpCodeInfo { addressing: "zpg,X", assembler: "LDY $LL,X", bytes: 2, cycles: "4" },
    /* 0xB5 */ OpCodeInfo { addressing: "zpg,X", assembler: "LDA $LL,X", bytes: 2, cycles: "4" },
    /* 0xB6 */ OpCodeInfo { addressing: "zpg,Y", assembler: "LDX $LL,Y", bytes: 2, cycles: "4" },
    /* 0xB7 */ OpCodeInfo { addressing: "zpg,Y", assembler: "LAX $LL,Y", bytes: 2, cycles: "4" },
    /* 0xB8 */ OpCodeInfo { addressing: "impl", assembler: "CLV", bytes: 1, cycles: "2" },
    /* 0xB9 */ OpCodeInfo { addressing: "abs,Y", assembler: "LDA $LLHH,Y", bytes: 3, cycles: "4+p" },
    /* 0xBA */ OpCodeInfo { addressing: "impl", assembler: "TSX", bytes: 1, cycles: "2" },
    /* 0xBB */ OpCodeInfo { addressing: "abs,Y", assembler: "LAS $LLHH,Y", bytes: 3, cycles: "4+p" },
    /* 0xBC */ OpCodeInfo { addressing: "abs,X", assembler: "LDY $LLHH,X", bytes: 3, cycles: "4+p" },
    /* 0xBD */ OpCodeInfo { addressing: "abs,X", assembler: "LDA $LLHH,X", bytes: 3, cycles: "4+p" },
    /* 0xBE */ OpCodeInfo { addressing: "abs,Y", assembler: "LDX $LLHH,Y", bytes: 3, cycles: "4+p" },
    /* 0xBF */ OpCodeInfo { addressing: "abs,Y", assembler: "LAX $LLHH,Y", bytes: 3, cycles: "4+p" },
    /* 0xC0 */ OpCodeInfo { addressing: "#", assembler: "CPY #$LL", bytes: 2, cycles: "2" },
    /* 0xC1 */ OpCodeInfo { addressing: "X,ind", assembler: "CMP ($LL,X)", bytes: 2, cycles: "6" },
    /* 0xC2 */ OpCodeInfo { addressing: "#", assembler: "NOP #$LL", bytes: 2, cycles: "2" },
    /* 0xC3 */ OpCodeInfo { addressing: "X,ind", assembler: "DCP ($LL,X)", bytes: 2, cycles: "8" },
    /* 0xC4 */ OpCodeInfo { addressing: "zpg", assembler: "CPY $LL", bytes: 2, cycles: "3" },
    /* 0xC5 */ OpCodeInfo { addressing: "zpg", assembler: "CMP $LL", bytes: 2, cycles: "3" },
    /* 0xC6 */ OpCodeInfo { addressing: "zpg", assembler: "DEC $LL", bytes: 2, cycles: "5" },
    /* 0xC7 */ OpCodeInfo { addressing: "zpg", assembler: "DCP $LL", bytes: 2, cycles: "5" },
    /* 0xC8 */ OpCodeInfo { addressing: "impl", assembler: "INY", bytes: 1, cycles: "2" },
    /* 0xC9 */ OpCodeInfo { addressing: "#", assembler: "CMP #$LL", bytes: 2, cycles: "2" },
    /* 0xCA */ OpCodeInfo { addressing: "impl", assembler: "DEX", bytes: 1, cycles: "2" },
    /* 0xCB */ OpCodeInfo { addressing: "#", assembler: "SBX #$LL", bytes: 2, cycles: "2" },
    /* 0xCC */ OpCodeInfo { addressing: "abs", assembler: "CPY $LLHH", bytes: 3, cycles: "4" },
    /* 0xCD */ OpCodeInfo { addressing: "abs", assembler: "CMP $LLHH", bytes: 3, cycles: "4" },
    /* 0xCE */ OpCodeInfo { addressing: "abs", assembler: "DEC $LLHH", bytes: 3, cycles: "6" },
    /* 0xCF */ OpCodeInfo { addressing: "abs", assembler: "DCP $LLHH", bytes: 3, cycles: "6" },
    /* 0xD0 */ OpCodeInfo { addressing: "rel", assembler: "BNE $LLHH", bytes: 2, cycles: "2+t+p" },
    /* 0xD1 */ OpCodeInfo { addressing: "ind,Y", assembler: "CMP ($LL),Y", bytes: 2, cycles: "5+p" },
    /* 0xD2 */ OpCodeInfo { addressing: "impl", assembler: "JAM", bytes: 1, cycles: "X" },
    /* 0xD3 */ OpCodeInfo { addressing: "ind,Y", assembler: "DCP ($LL),Y", bytes: 2, cycles: "8" },
    /* 0xD4 */ OpCodeInfo { addressing: "zpg,X", assembler: "NOP $LL,X", bytes: 2, cycles: "4" },
    /* 0xD5 */ OpCodeInfo { addressing: "zpg,X", assembler: "CMP $LL,X", bytes: 2, cycles: "4" },
    /* 0xD6 */ OpCodeInfo { addressing: "zpg,X", assembler: "DEC $LL,X", bytes: 2, cycles: "6" },
    /* 0xD7 */ OpCodeInfo { addressing: "zpg,X", assembler: "DCP $LL,X", bytes: 2, cycles: "6" },
    /* 0xD8 */ OpCodeInfo { addressing: "impl", assembler: "CLD", bytes: 1, cycles: "2" },
    /* 0xD9 */ OpCodeInfo { addressing: "abs,Y", assembler: "CMP $LLHH,Y", bytes: 3, cycles: "4+p" },
    /* 0xDA */ OpCodeInfo { addressing: "impl", assembler: "NOP", bytes: 1, cycles: "2" },
    /* 0xDB */ OpCodeInfo { addressing: "abs,Y", assembler: "DCP $LLHH,Y", bytes: 3, cycles: "7" },
    /* 0xDC */ OpCodeInfo { addressing: "abs,X", assembler: "NOP $LLHH,X", bytes: 3, cycles: "4+p" },
    /* 0xDD */ OpCodeInfo { addressing: "abs,X", assembler: "CMP $LLHH,X", bytes: 3, cycles: "4+p" },
    /* 0xDE */ OpCodeInfo { addressing: "abs,X", assembler: "DEC $LLHH,X", bytes: 3, cycles: "7" },
    /* 0xDF */ OpCodeInfo { addressing: "abs,X", assembler: "DCP $LLHH,X", bytes: 3, cycles: "7" },
    /* 0xE0 */ OpCodeInfo { addressing: "#", assembler: "CPX #$LL", bytes: 2, cycles: "2" },
    /* 0xE1 */ OpCodeInfo { addressing: "X,ind", assembler: "SBC ($LL,X)", bytes: 2, cycles: "6" },
    /* 0xE2 */ OpCodeInfo { addressing: "#", assembler: "NOP #$LL", bytes: 2, cycles: "2" },
    /* 0xE3 */ OpCodeInfo { addressing: "X,ind", assembler: "ISC ($LL,X)", bytes: 2, cycles: "8" },
    /* 0xE4 */ OpCodeInfo { addressing: "zpg", assembler: "CPX $LL", bytes: 2, cycles: "3" },
    /* 0xE5 */ OpCodeInfo { addressing: "zpg", assembler: "SBC $LL", bytes: 2, cycles: "3" },
    /* 0xE6 */ OpCodeInfo { addressing: "zpg", assembler: "INC $LL", bytes: 2, cycles: "5" },
    /* 0xE7 */ OpCodeInfo { addressing: "zpg", assembler: "ISC $LL", bytes: 2, cycles: "5" },
    /* 0xE8 */ OpCodeInfo { addressing: "impl", assembler: "INX", bytes: 1, cycles: "2" },
    /* 0xE9 */ OpCodeInfo { addressing: "#", assembler: "SBC #$LL", bytes: 2, cycles: "2" },
    /* 0xEA */ OpCodeInfo { addressing: "impl", assembler: "NOP", bytes: 1, cycles: "2" },
    /* 0xEB */ OpCodeInfo { addressing: "#", assembler: "SBC #$LL", bytes: 2, cycles: "2" },
    /* 0xEC */ OpCodeInfo { addressing: "abs", assembler: "CPX $LLHH", bytes: 3, cycles: "4" },
    /* 0xED */ OpCodeInfo { addressing: "abs", assembler: "SBC $LLHH", bytes: 3, cycles: "4" },
    /* 0xEE */ OpCodeInfo { addressing: "abs", assembler: "INC $LLHH", bytes: 3, cycles: "6" },
    /* 0xEF */ OpCodeInfo { addressing: "abs", assembler: "ISC $LLHH", bytes: 3, cycles: "6" },
    /* 0xF0 */ OpCodeInfo { addressing: "rel", assembler: "BEQ $LLHH", bytes: 2, cycles: "2+t+p" },
    /* 0xF1 */ OpCodeInfo { addressing: "ind,Y", assembler: "SBC ($LL),Y", bytes: 2, cycles: "5+p" },
    /* 0xF2 */ OpCodeInfo { addressing: "impl", assembler: "JAM", bytes: 1, cycles: "X" },
    /* 0xF3 */ OpCodeInfo { addressing: "ind,Y", assembler: "ISC ($LL),Y", bytes: 2, cycles: "8" },
    /* 0xF4 */ OpCodeInfo { addressing: "zpg,X", assembler: "NOP $LL,X", bytes: 2, cycles: "4" },
    /* 0xF5 */ OpCodeInfo { addressing: "zpg,X", assembler: "SBC $LL,X", bytes: 2, cycles: "4" },
    /* 0xF6 */ OpCodeInfo { addressing: "zpg,X", assembler: "INC $LL,X", bytes: 2, cycles: "6" },
    /* 0xF7 */ OpCodeInfo { addressing: "zpg,X", assembler: "ISC $LL,X", bytes: 2, cycles: "6" },
    /* 0xF8 */ OpCodeInfo { addressing: "impl", assembler: "SED", bytes: 1, cycles: "2" },
    /* 0xF9 */ OpCodeInfo { addressing: "abs,Y", assembler: "SBC $LLHH,Y", bytes: 3, cycles: "4+p" },
    /* 0xFA */ OpCodeInfo { addressing: "impl", assembler: "NOP", bytes: 1, cycles: "2" },
    /* 0xFB */ OpCodeInfo { addressing: "abs,Y", assembler: "ISC $LLHH,Y", bytes: 3, cycles: "7" },
    /* 0xFC */ OpCodeInfo { addressing: "abs,X", assembler: "NOP $LLHH,X", bytes: 3, cycles: "4+p" },
    /* 0xFD */ OpCodeInfo { addressing: "abs,X", assembler: "SBC $LLHH,X", bytes: 3, cycles: "4+p" },
    /* 0xFE */ OpCodeInfo { addressing: "abs,X", assembler: "INC $LLHH,X", bytes: 3, cycles: "7" },
    /* 0xFF */ OpCodeInfo { addressing: "abs,X", assembler: "ISC $LLHH,X", bytes: 3, cycles: "7" },
];
